const Attendance = require('../models/Attendance');
const Leave = require('../models/Leave');
const Fine = require('../models/Fine');
const User = require('../models/User');
const { sendWhatsAppNotification } = require('../utils/notification');

// Mark Daily Attendance (Admin)
exports.markAttendance = async (req, res) => {
    try {
        const { records } = req.body; // records: [{ studentId, status, date }]
        console.log(`[ATTENDANCE] Received ${records?.length || 0} records.`);

        for (const data of records) {
            const { studentId, status, date } = data;

            // Normalize to UTC Midnight regardless of input format
            const d = new Date(date);
            const utcDate = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));

            console.log(`[ATTENDANCE] Processing: ${studentId} -> ${status} on ${utcDate.toISOString()}`);

            // Mark attendance
            await Attendance.findOneAndUpdate(
                { studentId, date: utcDate },
                { status },
                { upsert: true, new: true }
            );

            // Special Automation Feature: Unauthorized Leave Detection
            if (status === 'Absent') {
                const leaveRequest = await Leave.findOne({
                    studentId,
                    status: 'Approved',
                    startDate: { $lte: utcDate },
                    endDate: { $gte: utcDate }
                });

                if (!leaveRequest) {
                    const fineReason = `Unauthorized Absence on ${utcDate.toISOString().split('T')[0]}`;
                    const existingFine = await Fine.findOne({ studentId, reason: fineReason });

                    if (!existingFine) {
                        const fine = new Fine({
                            studentId,
                            reason: fineReason,
                            amount: 50,
                            autoGenerated: true,
                            date: utcDate
                        });
                        await fine.save();

                        const student = await User.findById(studentId);
                        if (student) {
                            const adminMessage = `Alert: Student ${student.name} [Reg: ${student.registerNumber}] was absent without approved leave. Automated fine issued.`;
                            await sendWhatsAppNotification('AdminPhone_placeholder', adminMessage);
                        }
                    }
                }
            }
        }

        res.status(200).json({ message: 'Attendance marked successfully.' });
    } catch (error) {
        console.error('Attendance Mark Error:', error);
        res.status(500).json({ message: 'Error marking attendance.', error: error.message });
    }
};

// Get My Attendance (Student)
exports.getMyAttendance = async (req, res) => {
    try {
        const studentId = req.user.id;
        const attendance = await Attendance.find({ studentId }).sort({ date: -1 });
        res.status(200).json(attendance);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Calculate Attendance Percentage for a single student or all
exports.getAttendancePercentage = async (req, res) => {
    try {
        const { studentId } = req.params;
        const query = studentId ? { studentId } : {};

        const totalDays = await Attendance.countDocuments(query);
        const presentDays = await Attendance.countDocuments({ ...query, status: 'Present' });

        const percentage = totalDays > 0 ? (presentDays / totalDays) * 100 : 0;

        res.status(200).json({ studentId, totalDays, presentDays, percentage });
    } catch (error) {
        res.status(500).json({ message: 'Error calculating percentage.', error: error.message });
    }
};

// Get Dashboard Stats (Analytics for Admin)
exports.getAdminStats = async (req, res) => {
    try {
        const totalStudents = await User.countDocuments({ role: 'student' });
        const pendingLeaveRequests = await Leave.countDocuments({ status: 'Pending' });
        const totalFines = await Fine.aggregate([{ $group: { _id: null, total: { $sum: '$amount' } } }]);

        // Analytics for bar/pie charts (simplified)
        const attendanceTrend = await Attendance.aggregate([
            { $group: { _id: '$status', count: { $sum: 1 } } }
        ]);

        res.status(200).json({
            totalStudents,
            pendingLeaveRequests,
            totalFineAmount: totalFines[0]?.total || 0,
            attendanceTrend
        });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

const { exportToCSV } = require('../utils/csvExporter');

// Get Monthly Report (JSON or CSV)
exports.getMonthlyReport = async (req, res) => {
    try {
        const { month, year, format } = req.query; // format=csv or json
        const startDate = new Date(year, month - 1, 1);
        const endDate = new Date(year, month, 0);

        const reportData = await Attendance.find({
            date: { $gte: startDate, $lte: endDate }
        }).populate('studentId', 'name registerNumber');

        if (format === 'csv') {
            const csvData = reportData.map(r => ({
                StudentName: r.studentId.name,
                RegisterNumber: r.studentId.registerNumber,
                Date: r.date.toDateString(),
                Status: r.status
            }));
            return exportToCSV(res, csvData, `Monthly_Report_${month}_${year}.csv`);
        }

        res.status(200).json(reportData);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Get List of Students for Attendance Marking (Admin)
exports.getStudentList = async (req, res) => {
    try {
        const { year } = req.query;
        let query = { role: { $regex: /^student$/i } };

        if (year && (year === '2' || year === '3')) {
            query.year = parseInt(year);
        }

        const students = await User.find(query).select('name registerNumber year');
        console.log(`[GET_STUDENT_LIST] Query: ${JSON.stringify(query)} -> Found: ${students.length}`);
        res.status(200).json(students);
    } catch (error) {
        console.error('getStudentList Error:', error);
        res.status(500).json({ error: error.message });
    }
};

// Get List of Unauthorized Absences (Admin)
exports.getUnauthorizedAbsences = async (req, res) => {
    try {
        const unauthorizedFines = await Fine.find({ autoGenerated: true })
            .populate('studentId', 'name registerNumber')
            .sort({ date: -1 });
        res.status(200).json(unauthorizedFines);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Get Attendance for specific date (Admin)
exports.getAttendanceByDate = async (req, res) => {
    try {
        const { date } = req.params;
        const d = new Date(date);
        const utcDate = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));

        const records = await Attendance.find({ date: utcDate });
        res.status(200).json(records);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Get Daily Summaries for History (Admin)
exports.getDailySummaries = async (req, res) => {
    try {
        const summaries = await Attendance.aggregate([
            {
                $lookup: {
                    from: 'users',
                    localField: 'studentId',
                    foreignField: '_id',
                    as: 'student'
                }
            },
            { $unwind: '$student' },
            {
                $group: {
                    _id: {
                        date: "$date",
                        year: "$student.year"
                    },
                    presentCount: { $sum: { $cond: [{ $eq: ["$status", "Present"] }, 1, 0] } },
                    absentCount: { $sum: { $cond: [{ $eq: ["$status", "Absent"] }, 1, 0] } }
                }
            },
            {
                $project: {
                    _id: 0,
                    date: "$_id.date",
                    year: "$_id.year",
                    presentCount: 1,
                    absentCount: 1
                }
            },
            { $sort: { date: -1, year: 1 } }
        ]);
        res.status(200).json(summaries);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};
