const Fine = require('../models/Fine');
const AuditLog = require('../models/AuditLog');

// Add Manual Fine (Admin)
exports.addFine = async (req, res) => {
    try {
        const { studentId, reason, amount } = req.body;

        const newFine = new Fine({ studentId, reason, amount, autoGenerated: false });
        await newFine.save();

        // Audit Log Entry
        const auditLog = new AuditLog({
            adminId: req.user.id,
            action: 'Fine Manually Added',
            targetId: studentId,
            details: { reason, amount }
        });
        await auditLog.save();

        res.status(201).json({ message: 'Fine added successfully.', fine: newFine });
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Get Fine History for a single student (Student)
exports.getMyFines = async (req, res) => {
    try {
        const fines = await Fine.find({ studentId: req.user.id }).sort({ date: -1 });
        res.status(200).json(fines);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};

// Get All Fines (Admin)
exports.getAllFines = async (req, res) => {
    try {
        const fines = await Fine.find().populate('studentId', 'name registerNumber').sort({ date: -1 });
        res.status(200).json(fines);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
};
