
const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Attendance = require('./models/Attendance');
const Fine = require('./models/Fine');
const Leave = require('./models/Leave');

dotenv.config();

const seedExtraData = async () => {
    try {
        console.log('--- SEEDING EXTRA DEMO DATA ---');
        await mongoose.connect(process.env.MONGO_URI);

        // 1. Clear existing data (but keep users)
        await Attendance.deleteMany({});
        await Fine.deleteMany({});
        await Leave.deleteMany({});
        console.log('Cleared Attendance, Fines, and Leaves.');

        const students = await User.find({ role: 'student' });
        if (students.length === 0) {
            console.log('No students found! Run seed.js first.');
            process.exit(1);
        }

        // 2. Seed Attendance for last 7 days
        console.log('Seeding attendance...');
        for (let i = 0; i < 7; i++) {
            const date = new Date();
            date.setDate(date.getDate() - i);

            for (const student of students) {
                // 90% attendance rate
                const status = Math.random() > 0.1 ? 'Present' : 'Absent';
                await new Attendance({
                    studentId: student._id,
                    date: date,
                    status: status,
                    year: student.year
                }).save();
            }
        }

        // 3. Seed some Fines
        console.log('Seeding fines...');
        for (let i = 0; i < 10; i++) {
            const student = students[Math.floor(Math.random() * students.length)];
            await new Fine({
                studentId: student._id,
                amount: Math.floor(Math.random() * 500) + 100,
                reason: 'Unauthorized Absence / Late Entry',
                date: new Date(),
                autoGenerated: Math.random() > 0.5
            }).save();
        }

        // 4. Seed some Leaves
        console.log('Seeding leave requests...');
        for (let i = 0; i < 5; i++) {
            const student = students[Math.floor(Math.random() * students.length)];
            await new Leave({
                studentId: student._id,
                type: Math.random() > 0.5 ? 'Leave' : 'OD',
                reason: 'Family Function / External Symposium',
                startDate: new Date(),
                endDate: new Date(),
                status: 'Pending'
            }).save();
        }

        console.log('--- EXTRA DATA SEEDED SUCCESSFULLY ---');
        process.exit(0);
    } catch (error) {
        console.error('SEEDING ERROR:', error);
        process.exit(1);
    }
};

seedExtraData();
