import React, { useState, useEffect } from 'react';
import axios from 'axios';
import API_BASE_URL from '../config';
import {
    CreditCard,
    PlusCircle,
    Search,
    CheckCircle,
    AlertCircle,
    TrendingDown,
    Clock,
    ArrowRight
} from 'lucide-react';

const FineManagement = () => {
    const [fines, setFines] = useState([]);
    const [students, setStudents] = useState([]);
    const [loading, setLoading] = useState(true);
    const [formData, setFormData] = useState({ studentId: '', reason: '', amount: '' });
    const [statusMsg, setStatusMsg] = useState({ type: '', text: '' });
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        fetchFines();
        fetchStudents();
    }, []);

    const fetchFines = async () => {
        try {
            const response = await axios.get(`${API_BASE_URL}/fine/all`);
            setFines(response.data);
        } catch (error) {
            console.error(error);
        } finally {
            setLoading(false);
        }
    };

    const fetchStudents = async () => {
        try {
            const response = await axios.get(`${API_BASE_URL}/attendance/student-list`);
            setStudents(response.data);
        } catch (error) {
            console.error(error);
        }
    };

    const handleAddFine = async (e) => {
        e.preventDefault();
        setSubmitting(true);
        setStatusMsg({ type: '', text: '' });

        try {
            await axios.post(`${API_BASE_URL}/fine/add`, formData);
            setStatusMsg({ type: 'success', text: 'Adhoc Fine Applied Successfully!' });
            setFormData({ studentId: '', reason: '', amount: '' });
            fetchFines();
        } catch (error) {
            setStatusMsg({ type: 'error', text: 'Failed to apply fine.' });
        } finally {
            setSubmitting(false);
        }
    };

    const totalFines = fines.reduce((sum, f) => sum + f.amount, 0);

    return (
        <div className="p-8 max-w-7xl mx-auto space-y-10 animate-in fade-in duration-500">
            <div className="flex justify-between items-end">
                <div>
                    <h2 className="text-3xl font-bold text-white tracking-tight">Revenue & Fine Control</h2>
                    <p className="text-slate-500 font-medium mt-1">Manage departmental penalties and outstanding student dues</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                <div className="glass-card p-8 border-l-4 border-l-rose-500 group relative overflow-hidden">
                    <div className="absolute -right-4 -top-4 opacity-5 group-hover:opacity-10 transition-opacity">
                        <CreditCard size={150} />
                    </div>
                    <div className="relative z-10 space-y-2">
                        <p className="text-[10px] font-black text-rose-500 uppercase tracking-widest">Total Outstanding Revenue</p>
                        <h3 className="text-4xl font-black text-white tracking-tighter">₹{totalFines}</h3>
                        <div className="pt-4 flex items-center gap-2 text-rose-400 text-xs font-bold animate-pulse">
                            <TrendingDown size={14} />
                            <span>System defined: ₹{fines.filter(f => f.autoGenerated).reduce((s, f) => s + f.amount, 0)}</span>
                        </div>
                    </div>
                </div>

                <div className="lg:col-span-2 glass-card p-10 bg-gradient-to-br from-indigo-900/10 to-transparent">
                    <h3 className="text-lg font-black text-white mb-8 flex items-center gap-3">
                        <PlusCircle size={20} className="text-blue-500" />
                        Impose Adhoc Penalty
                    </h3>
                    {statusMsg.text && (
                        <div className={`mb-8 p-4 rounded-xl flex items-center gap-3 animate-in zoom-in-95 ${statusMsg.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-rose-500/10 border-rose-500/20 text-rose-400'
                            }`}>
                            <CheckCircle size={18} />
                            <span className="text-xs font-bold uppercase tracking-wider">{statusMsg.text}</span>
                        </div>
                    )}
                    <form onSubmit={handleAddFine} className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div className="space-y-2">
                            <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest px-1">Target Student</label>
                            <select
                                required
                                value={formData.studentId}
                                onChange={(e) => setFormData({ ...formData, studentId: e.target.value })}
                                className="w-full h-12 px-4 rounded-xl bg-white/5 border border-white/10 text-white text-xs font-medium focus:border-blue-500 outline-none cursor-pointer"
                            >
                                <option value="" className="bg-[#020617]">Select Registered Student</option>
                                {students.map(s => <option key={s._id} value={s._id} className="bg-[#020617]">{s.name} ({s.registerNumber})</option>)}
                            </select>
                        </div>
                        <div className="space-y-2">
                            <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest px-1">Penalty Amount (₹)</label>
                            <input
                                type="number"
                                required
                                placeholder="0.00"
                                value={formData.amount}
                                onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                                className="w-full h-12 px-4 rounded-xl bg-white/5 border border-white/10 text-white text-xs font-medium focus:border-blue-500 outline-none"
                            />
                        </div>
                        <div className="space-y-2 flex flex-col">
                            <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest px-1">Reason Statement</label>
                            <input
                                type="text"
                                required
                                placeholder="Misconduct, Lost Property..."
                                value={formData.reason}
                                onChange={(e) => setFormData({ ...formData, reason: e.target.value })}
                                className="w-full h-12 px-4 rounded-xl bg-white/5 border border-white/10 text-white text-xs font-medium focus:border-blue-500 outline-none"
                            />
                        </div>
                        <div className="md:col-span-3 pt-2">
                            <button
                                type="submit"
                                disabled={submitting}
                                className="w-full h-12 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-black text-xs uppercase tracking-widest shadow-xl shadow-blue-600/20 transition-all flex items-center justify-center gap-2 active:scale-[0.98] disabled:opacity-50"
                            >
                                {submitting ? <Clock className="animate-spin" size={16} /> : <PlusCircle size={16} />}
                                Issue Official Penalty
                            </button>
                        </div>
                    </form>
                </div>
            </div>

            <div className="glass-card p-0 overflow-hidden shadow-2xl">
                <div className="p-8 border-b border-white/5 bg-white/2 flex items-center gap-3">
                    <Clock size={20} className="text-slate-400" />
                    <h3 className="text-sm font-black text-white uppercase tracking-widest">Active Fine Ledger</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left">
                        <thead className="bg-[#020617]/50">
                            <tr className="text-[10px] font-black uppercase text-slate-500 tracking-[0.2em] border-b border-white/5">
                                <th className="px-10 py-6">Student Identity</th>
                                <th className="px-10 py-6">Penalty Factor</th>
                                <th className="px-10 py-6">Record Date</th>
                                <th className="px-10 py-6 text-right">Dues Payable</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5">
                            {fines.length === 0 ? (
                                <tr><td colSpan="4" className="py-20 text-center text-slate-500 font-bold italic tracking-wide">No penalties have been recorded yet.</td></tr>
                            ) : fines.map((fine, i) => (
                                <tr key={i} className="hover:bg-white/2 transition-colors">
                                    <td className="px-10 py-6">
                                        <div className="flex items-center gap-4">
                                            <div className="w-9 h-9 rounded-lg bg-white/5 flex items-center justify-center text-blue-400 font-bold border border-white/5 text-[10px]">
                                                {fine.studentId?.name?.[0]}
                                            </div>
                                            <div>
                                                <p className="text-sm font-black text-white">{fine.studentId?.name}</p>
                                                <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">{fine.studentId?.registerNumber}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-10 py-6">
                                        <div className="flex flex-col gap-1.5">
                                            <div className="flex items-center gap-2">
                                                <span className={`px-2 py-0.5 rounded text-[9px] font-black uppercase text-white ${fine.autoGenerated ? 'bg-rose-600' : 'bg-amber-600'}`}>
                                                    {fine.autoGenerated ? 'SYS' : 'ADHOC'}
                                                </span>
                                                <p className="text-sm font-bold text-slate-300">{fine.reason}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="px-10 py-6 text-xs text-slate-500 font-black uppercase tracking-widest">
                                        {new Date(fine.date).toLocaleDateString()}
                                    </td>
                                    <td className="px-10 py-6 text-right">
                                        <p className="text-lg font-black text-white tracking-tighter">₹{fine.amount}</p>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
};

export default FineManagement;
