const mongoose = require('mongoose');

const fineSchema = new mongoose.Schema({
    studentId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    reason: { type: String, required: true },
    amount: { type: Number, required: true },
    date: { type: Date, default: Date.now },
    autoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

module.exports = mongoose.model('Fine', fineSchema);
